spring:
  application:
    name: authentication
  main:
    allow-circular-references: true
  datasource:
    url: jdbc:postgresql://localhost:5432/auth
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
  jpa:
    database: POSTGRESQL
    hibernate:
      #ddl-auto possible values: none, validate, update, create-drop
      ddl-auto: update
    show-sql: true
server:
  port: 8989
eureka:
  client:
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/