debug: true
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    reactor.netty.http.client: DEBUG
server:
  port: '8087'
spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
  application:
    name: api-gateway
  gateway:
    excludedURLsNew: /api/v1/users/authenticate,/signin,/signup,/forgotpsw
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
management:
  endpoints:
    web:
      exposure:
        include: '*'
eureka:
  client:
    serviceUrl:
      defaultZone: ${DEUREKA_SERVER}
  instance:
    prefer-ip-address: 'true'